### ISSUE TITLE
Incorrect `x-typescript-types` header when main entry is fetched directly

### ISSUE THREAD

**Issue by marvinhagemeister** [esm-dev/esm.sh#578]
## Failing module

- **GitHub**: https://github.com/KaTeX/KaTeX
- **npm**: https://npmjs.com/package/katex

```js
import * as katex from "https://esm.sh/katex@0.16.4/dist/katex.mjs"
```

## Error message

Not an error per se, but deno is unable to find the correct typings. See discussion at https://github.com/denoland/deno/issues/18583

The problem is that deno resolves the main package entry itself and fetches `https://esm.sh/katex@0.16.4/dist/katex.mjs` directly instead of `https://esm.sh/katex@0.16.4`. The latter has the correct `x-typescript-types` header, but the former points to an invalid one. Given that the former is an exact match of a main entry point I was expecting the main entry point to be resolved against `@types/katex`.

| URL | x-typescript-types | Status |
|---|---|---|
| https://esm.sh/katex@0.16.4/dist/katex.mjs | https://esm.sh/v113/@types/katex@~0.16/dist/katex.mjs~.d.ts | wrong |
| https://esm.sh/katex@0.16.4 | https://esm.sh/v113/@types/katex@~0.16/index.d.ts | correct |

`katax` package.json:

```json
{
  "name": "katex",
  "version": "0.16.4",
  "main": "dist/katex.js",
  "exports": {
    ".": {
      "require": "./dist/katex.js",
      "import": "./dist/katex.mjs" // <-- This file is fetched directly by deno
    },
    // ...
  }
}
```

`@types/katax` package.json:

```json
{
    "name": "@types/katex",
    "version": "0.16.0",
    "main": "",
    "types": "index.d.ts",
    //...
}
```

## Additional info

- **esm.sh version**: latest - whatever is deployed on https://esm.sh
- **Deno version**: 1.32.3
- Related issue: https://github.com/denoland/deno/issues/18583

**Comment by ije** [comment]
i believe this has been fixed in https://github.com/esm-dev/esm.sh/commit/c70aa0f32bfea957c3e3894640efc74188e1f525, will release v114 very soon

**Comment by marvinhagemeister** [comment]
Looks like it's not fully resolved. I can reproduce the incorrect header value in `main` too (commit: c65507a838d3825433662ff7ccd3de83ad22c1e8).

**Comment by iuioiua** [comment]
Likely related: #572

**Comment by ije** [comment]
thanks for fixing this!

**Comment by marvinhagemeister** [comment]
@ije Awesome, thanks for the merge! Happy to help out!

@iuioiua I dug a bit into that but I can't find a fault in `esm.sh` for that. It seems like something goes wrong in deno when building the URLs.

**Comment by iuioiua** [comment]
That'd be amazing, @marvinhagemeister!
