### ISSUE TITLE
Failed to import - @bokuweb/zstd-wasm

### ISSUE THREAD

**Issue by Xyah3PBeHB** [esm-dev/esm.sh#602]
## Failing module

- **GitHub**: https://github.com/bokuweb/zstd-wasm
- **npm**: https://npmjs.com/package/@bokuweb/zstd-wasm

```js
import { init } from "https://esm.sh/@bokuweb/zstd-wasm"
init()
```

## Error message

After `onload` I got this:

```
Uncaught (in promise) Error: Dynamic require of "data:text/javascript,const data=await fetch('https://esm.sh/@bokuweb/zstd-wasm@0.0.20/dist/web/wasm/zstd.wasm').then(r=>r.arrayBuffer());export default new WebAssembly.Module(data)" is not supported
    at index.web.ts:7:2
    at index.web.ts:7:2
    at Generator.next (<anonymous>)
    at index.web.ts:7:2
    at new Promise (<anonymous>)
    at pe (index.web.ts:7:2)
    at Module.Be (index.web.ts:7:2)
    at <anonymous>:1:64
```

## Additional info

- **esm.sh version**: v115~
- **Browser version**: Chromium 102

**Comment by ije** [comment]
i fixed the dynamic require error, but you need to point out the wasm url (require wasm module doesn't work currently)
```js
await init("https://esm.sh/@bokuweb/zstd-wasm@0.0.20/dist/esm/wasm/zstd.wasm");
```

**Comment by Xyah3PBeHB** [comment]
> i fixed the dynamic require error, but you need to point out the wasm url (require wasm module doesn't work currently)
> 
> ```js
> await init("https://esm.sh/@bokuweb/zstd-wasm@0.0.20/dist/esm/wasm/zstd.wasm");
> ```

Now it throws this error. 
```
index.web.ts:7 Uncaught (in promise) RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at index.web.ts:7:2
    at index.web.ts:7:2
    at index.web.ts:7:2
    at Generator.next (<anonymous>)
    at index.web.ts:7:2
    at new Promise (<anonymous>)
    at LA (index.web.ts:7:2)
    at vA (index.web.ts:7:2)
    at index.html:32:839
```

I tried downgrading the library version and PIN to an older esm.sh version and still getting this error, but I'm sure it was ok a month ago.
