### ISSUE TITLE
Failed to import - gh/bablr-lang/bablr-vm

### ISSUE THREAD

**Issue by conartist6** [esm-dev/esm.sh#761]
## Failing module

- **GitHub**: https://github.com/bablr-lang/bablr-vm

```js
import { parseCSTML } from 'https://esm.sh/gh/bablr-lang/bablr-vm@709bd7899c585c18194baf9b730e38702272fa90';
```

## Error message

After running `deno run` I got this:

```
error: Import 'https://esm.sh/v134/@bablr/boot-helpers@0.0.0/denonext/template.js' failed: 500 Internal Server Error
    at https://esm.sh/gh/bablr-lang/bablr-vm@709bd7899c585c18194baf9b730e38702272fa90:4:8
```

The error indicates that the wrong URL is being imported. The correct URL to import would be:

```
https://esm.sh/v134/gh/bablr-lang/boot-helpers@1551598bc7257481089d06839eeec2e26885bbb2/es2022/lib/template.js
```

This is because my `package.json` contains:

```json
  "dependencies": {
    "@bablr/boot-helpers": "github:bablr-lang/boot-helpers#1551598bc7257481089d06839eeec2e26885bbb2",
  },
```

## Additional info

- **esm.sh version**: 134

**Comment by ije** [comment]
thanks for the details, i will look into

**Comment by conartist6** [comment]
I have a suspicion that pnpm is involved, as `pnpm` is the only thing that knows that the version the resolved github package claims to be is `0.0.0`.

From `pnpm-lock.yaml`:
```yaml
  github.com/bablr-lang/boot-helpers/1551598bc7257481089d06839eeec2e26885bbb2:
    resolution: {tarball: https://codeload.github.com/bablr-lang/boot-helpers/tar.gz/1551598bc7257481089d06839eeec2e26885bbb2}
    name: '@bablr/boot-helpers'
    version: 0.0.0
    engines: {node: '>=12.0.0'}
```

**Comment by conartist6** [comment]
@ije I would pay you $500 on Open Collective for a fix for this issue. I really need and want it, but I don't have the time or Go knowledge. Are you interested?

**Comment by ije** [comment]
thanks, I will look into it tomorrow

**Comment by conartist6** [comment]
Amazing, thanks! Easy money, I hope.

**Comment by ije** [comment]
update: i just fixed the build error, however i got anthor error that esm.sh can not handle

<img width="1084" alt="Screenshot 2024-04-17 at 20 45 41" src="https://github.com/esm-dev/esm.sh/assets/2883484/2c2d4f4f-0742-47a4-9cb1-6b06ae8053a9">

 here is the related code: https://github.com/bablr-lang/bablr-vm/blob/709bd7899c585c18194baf9b730e38702272fa90/lib/path.js#L36

**Comment by conartist6** [comment]
I think that should be fine. The bug report is made with a fairly old copy of my code that calls from esm into cjs, but the current copies that I care deeply to get deployed do not.

**Comment by conartist6** [comment]
Just got finished making it: https://gist.github.com/conartist6/3e3ceb0e43f3686da8641d5784212f24

I'm still getting an error but it could well be my fault, so I'm investigating.

**Comment by ije** [comment]
seems it works now, please give a try (`--reload` flag may be needed)

<img width="1139" alt="Screenshot 2024-04-18 at 03 40 34" src="https://github.com/esm-dev/esm.sh/assets/2883484/b18c5eca-541c-490c-bbd2-ad21b9fe25a6">

graph:

```
$ deno info --reload https://esm.sh/gh/bablr-lang/bablr@279a549d0bf730e7d8ed008386ff157fc5b0fecd/lib/enhanceable.js

local: /Users/x/Library/Caches/deno/deps/https/esm.sh/5cb68b1b6ba8a153c009471c050c23e068f34e065b0990c3f0ebb5967d43471c
type: JavaScript
dependencies: 53 unique
size: 131.82KB

https://esm.sh/gh/bablr-lang/bablr@279a549d0bf730e7d8ed008386ff157fc5b0fecd/lib/enhanceable.js (204B)
└─┬ https://esm.sh/v135/gh/bablr-lang/bablr@279a549d0bf730e7d8ed008386ff157fc5b0fecd/denonext/lib/enhanceable.js (1.9KB)
  ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm@26569fe6bb75cab64f0831766eadac9c1c19f91d (311B)
  │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/map.js (4.1KB)
  │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/filter.js (4.12KB)
  │ └─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm@26569fe6bb75cab64f0831766eadac9c1c19f91d/denonext/agast-vm.mjs (10.67KB)
  │   ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675 (425B)
  │   │ ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/builders.js (7.44KB)
  │   │ │ ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/template (312B)
  │   │ │ │ ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/builders.js (2.34KB)
  │   │ │ │ └─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/template.js (816B)
  │   │ │ │   └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/builders.js *
  │   │ │ ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/shorthand (314B)
  │   │ │ │ ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/builders.js *
  │   │ │ │ └─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/shorthand.js (1.14KB)
  │   │ │ │   └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/builders.js *
  │   │ │ └── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/languages.js (572B)
  │   │ ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/run.js (931B)
  │   │ │ ├─┬ https://esm.sh/v135/gh/bablr-lang/coroutine@2342d82713731288034df588f11f540d1b76603d (312B)
  │   │ │ │ └── https://esm.sh/v135/gh/bablr-lang/coroutine@2342d82713731288034df588f11f540d1b76603d/denonext/coroutine.mjs (764B)
  │   │ │ └─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/print (200B)
  │   │ │   └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/print.js (973B)
  │   │ └─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/agast-vm-helpers.mjs (3.92KB)
  │   │   ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/tree (578B)
  │   │   │ ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs (1.66KB)
  │   │   │ ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/builders.js *
  │   │   │ ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/stream.js (2.33KB)
  │   │   │ │ └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/print.js *
  │   │   │ ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/print.js *
  │   │   │ └─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/tree.js (4.37KB)
  │   │   │   ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs *
  │   │   │   ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/builders.js *
  │   │   │   ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/stream.js *
  │   │   │   └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/print.js *
  │   │   ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/builders (206B)
  │   │   │ └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/builders.js *
  │   │   ├── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/builders.js *
  │   │   └── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/run.js *
  │   ├── https://esm.sh/v135/gh/bablr-lang/coroutine@2342d82713731288034df588f11f540d1b76603d *
  │   ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/builders *
  │   ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/print *
  │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/map.js *
  │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/filter.js *
  │   ├─┬ https://esm.sh/v135/gh/bablr-lang/weak-stack@b153132f150f3927f75af0645614c986c7610ab9 (317B)
  │   │ └── https://esm.sh/v135/gh/bablr-lang/weak-stack@b153132f150f3927f75af0645614c986c7610ab9/denonext/weak-stack.mjs (728B)
  │   ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/tree *
  │   ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/facades (210B)
  │   │ └── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/facades.js (547B)
  │   └─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/stream (305B)
  │     ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/print.js *
  │     └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/stream.js *
  ├─┬ https://esm.sh/v135/gh/bablr-lang/bablr-vm@2ffaaddcfa78484afc84a1a99d291727d637b8e8 (393B)
  │ ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs *
  │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/starts-with-seq.js (6.78KB)
  │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/is-string.js (794B)
  │ └─┬ https://esm.sh/v135/gh/bablr-lang/bablr-vm@2ffaaddcfa78484afc84a1a99d291727d637b8e8/denonext/bablr-vm.mjs (8.21KB)
  │   ├── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675 *
  │   ├── https://esm.sh/v135/gh/bablr-lang/coroutine@2342d82713731288034df588f11f540d1b76603d *
  │   ├─┬ https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/grammar (436B)
  │   │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/every.js (4.14KB)
  │   │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/is-string.js *
  │   │ ├─┬ https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/denonext/object.js (1.11KB)
  │   │ │ └── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/map.js *
  │   │ └─┬ https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/denonext/grammar.js (1.73KB)
  │   │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/every.js *
  │   │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/is-string.js *
  │   │   └── https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/denonext/object.js *
  │   ├─┬ https://esm.sh/v135/gh/bablr-lang/regex-vm@26c0151f4dc441d35d722a2996db28e3c0a4e5c0 (584B)
  │   │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/peekerate.js (4.95KB)
  │   │ ├─┬ https://esm.sh/v135/gh/bablr-lang/regex-vm@26c0151f4dc441d35d722a2996db28e3c0a4e5c0/denonext/internal/engine.js (3.56KB)
  │   │ │ └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/tree *
  │   │ ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs *
  │   │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/object-from.js (4.26KB)
  │   │ ├── https://esm.sh/v135/functional-red-black-tree@1.0.1/denonext/functional-red-black-tree.mjs (10.2KB)
  │   │ └─┬ https://esm.sh/v135/gh/bablr-lang/regex-vm@26c0151f4dc441d35d722a2996db28e3c0a4e5c0/denonext/regex-vm.mjs (7.63KB)
  │   │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/peekerate.js *
  │   │   ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs *
  │   │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/object-from.js *
  │   │   ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/tree *
  │   │   ├── https://esm.sh/v135/functional-red-black-tree@1.0.1/denonext/functional-red-black-tree.mjs *
  │   │   └── https://esm.sh/v135/gh/bablr-lang/regex-vm@26c0151f4dc441d35d722a2996db28e3c0a4e5c0/denonext/internal/engine.js *
  │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/starts-with-seq.js *
  │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/is-string.js *
  │   ├── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/facades *
  │   ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs *
  │   └── https://esm.sh/v135/gh/bablr-lang/weak-stack@b153132f150f3927f75af0645614c986c7610ab9 *
  ├── https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/grammar *
  ├─┬ https://esm.sh/v135/gh/bablr-lang/bablr-vm-strategy-parse@c8c7ae70f54bef0c8d95407027c0dc25da656a6b (428B)
  │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/is-string.js *
  │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/equal.js (8.57KB)
  │ ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs *
  │ └─┬ https://esm.sh/v135/gh/bablr-lang/bablr-vm-strategy-parse@c8c7ae70f54bef0c8d95407027c0dc25da656a6b/denonext/bablr-vm-strategy-parse.mjs (6.69KB)
  │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/is-string.js *
  │   ├── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675 *
  │   ├── https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/grammar *
  │   ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/path (198B)
  │   │ └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/denonext/path.js (401B)
  │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/equal.js *
  │   ├── https://esm.sh/v135/@iter-tools/imm-stack@1.1.0/denonext/imm-stack.mjs *
  │   ├── https://esm.sh/v135/gh/bablr-lang/coroutine@2342d82713731288034df588f11f540d1b76603d *
  │   └── https://esm.sh/v135/gh/bablr-lang/weak-stack@b153132f150f3927f75af0645614c986c7610ab9 *
  ├─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/builders (322B)
  │ ├── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/languages.js *
  │ └── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/builders.js *
  ├─┬ https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/source (264B)
  │ ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/slice.js (6.36KB)
  │ └─┬ https://esm.sh/v135/gh/bablr-lang/bablr-helpers@7315ea97e7a5fd3890ba76ea50ac689d01cbc446/denonext/source.js (798B)
  │   ├── https://esm.sh/v135/iter-tools-es@7.5.3/denonext/methods/slice.js *
  │   └── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/tree *
  ├── https://esm.sh/v135/gh/bablr-lang/agast-helpers@caaa3389b422a03bc0f79e377fb499278bcd9109/tree *
  └─┬ https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/run (311B)
    ├── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/builders.js *
    └── https://esm.sh/v135/gh/bablr-lang/agast-vm-helpers@06490d8a33a192a39df2cd35ea97292d23f63675/denonext/run.js *
```

**Comment by ije** [comment]
thanks for your big sponsor! means a lot for me! if you have any question of using the cdn, i glad to help! thanks!
